name: 'Terraform'

on: repository_dispatch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -var="image_id=${{ github.event.client_payload.image_id }}"

    - name: Terraform Apply
      if: github.event.action == 'apply'
      env:
        TF_VAR_USER_NAME: ${{ secrets.USER_NAME }}
        TF_VAR_PASSWORD: ${{ secrets.PASSWORD }}
        TF_VAR_TENANT_NAME: ${{ secrets.TENANT_NAME }}
        TF_VAR_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      run: terraform apply -var="image_id=${{ github.event.client_payload.image_id }}" -auto-approve

    - name: Terraform Destroy
      if: github.event.action == 'destroy'
      run: terraform destroy -auto-approve
